name: Build & Deploy

on:
  push:
    branches: ["*"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Build WASM
        run: wasm-pack build --target web --release --no-default-features

      - name: Prepare artifact
        run: |
          BRANCH_NAME=${GITHUB_REF_NAME##refs/heads/}
          mkdir -p dist/$BRANCH_NAME
          mv index.html dist/$BRANCH_NAME/
          mv pkg dist/$BRANCH_NAME/
          mv assets dist/$BRANCH_NAME/

      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
